/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        /**
         * Brand accent — a deep petrol blue, generated on a perceptually even
         * OKLCH ramp (hue 248, chroma held under 0.12 so it reads considered
         * rather than neon). It deliberately OVERRIDES Tailwind's stock
         * `indigo`, which is a high-chroma violet-blue (#4f46e5) — the single
         * most recognisable "generated by AI" tell in a UI, and the colour this
         * product happened to be built on across ~520 usages.
         *
         * Overriding the ramp instead of renaming 520 classes means one edit
         * repaints the whole product coherently, and the dark-mode override
         * sheet in index.css (which targets `.dark .text-indigo-600` and
         * friends by name) keeps working untouched.
         *
         * `brand` is the same ramp under the name new code should use.
         * `indigo` is kept as the legacy alias.
         */
        indigo: {
          50: '#f3f8fe',
          100: '#e1eefc',
          200: '#c3def8',
          300: '#9ac5ef',
          400: '#6fa7dd',
          500: '#488ac5',
          600: '#2b6faa',
          700: '#1d588a',
          800: '#17456d',
          900: '#143755',
          950: '#081f32',
        },
        brand: {
          50: '#f3f8fe',
          100: '#e1eefc',
          200: '#c3def8',
          300: '#9ac5ef',
          400: '#6fa7dd',
          500: '#488ac5',
          600: '#2b6faa',
          700: '#1d588a',
          800: '#17456d',
          900: '#143755',
          950: '#081f32',
        },
        /**
         * The workspace's own palette. TenantProvider writes these onto :root
         * from the tenant's branding tokens, so `bg-workspace`, `text-workspace`
         * and `ring-workspace` follow whichever agency is signed in — one build
         * serves every customer, and changing a palette is a config edit rather
         * than a deploy.
         *
         * Plain `var(...)` rather than `hsl(var(...))` like the shadcn tokens
         * below: these are stored as hex, which is what a colour picker in the
         * settings screen produces and what a non-technical admin can paste
         * from a brand guide.
         */
        workspace: {
          DEFAULT: 'var(--brand)',
          contrast: 'var(--brand-contrast)',
          accent: 'var(--accent-color)',
          sidebar: 'var(--sidebar)',
          'sidebar-text': 'var(--sidebar-text)',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px) translateX(-50%)' },
          to: { opacity: '1', transform: 'translateY(0) translateX(-50%)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
